name: Java Maven CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all files are checked out

      - name: Set up JDK 22.0.1
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22.0.1'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file ./pom.xml

      - name: Run Tests
        run: mvn -f ./pom.xml test

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-app
          path: target/*.jar
