name: Build and Test Java Maven Project

# Trigger the workflow on push to the main branch and pull requests
on:
  push:
    branches:
      - main  # Change this to your default branch if it's not "main"
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3  # Action to checkout the code from the repository

      # Step 2: Set up Java Development Kit (JDK 17 in this case)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # You can change the version to your project's requirement

      # Step 3: Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository  # Cache Maven dependencies
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Cache key based on pom.xml changes
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project using Maven
      - name: Build with Maven
        run: mvn clean install --no-transfer-progress  # Build the project

      # Optional: Step 5: Run tests (Uncomment if you want to run tests)
      # - name: Run tests with Maven
      #   run: mvn test --no-transfer-progress

      # Optional: Step 6: Package the project (if applicable)
      # - name: Package with Maven
      #   run: mvn package --no-transfer-progress
